//! Postal `frpc.toml` renderer (frp v0.61 TOML).
//!
//! Always `type = "https"` to `127.0.0.1` so the relay carries ciphertext and
//! the resident agent terminates TLS on loopback. Not a k2-core render copy:
//! hostname is `{label}.postal.bot` via `customDomains`, proxy name `postal-*`.

use std::fmt;
use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};

use crate::csr::TUNNEL_DIR;
use crate::san::{hostname_for_label, SanError};

/// Shared k2e-01 frps (K8). Override with `P5_FRP_SERVER`.
pub const DEFAULT_FRP_SERVER: &str = "178.156.232.105";
/// frps `bindPort`.
pub const DEFAULT_FRP_PORT: u16 = 7000;
pub const FRPC_TOML_FILE: &str = "frpc.toml";

#[derive(Clone)]
pub struct FrpcSpec {
    pub label: String,
    pub local_port: u16,
    pub server_addr: String,
    pub server_port: u16,
    pub token: Option<String>,
}

impl fmt::Debug for FrpcSpec {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("FrpcSpec")
            .field("label", &self.label)
            .field("local_port", &self.local_port)
            .field("server_addr", &self.server_addr)
            .field("server_port", &self.server_port)
            .field("token", &self.token.as_ref().map(|_| "<redacted>"))
            .finish()
    }
}

#[derive(Debug)]
pub enum RenderError {
    San(SanError),
    Io(io::Error),
}

impl fmt::Display for RenderError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::San(err) => write!(f, "{err}"),
            Self::Io(err) => write!(f, "frpc.toml io: {err}"),
        }
    }
}

impl std::error::Error for RenderError {}

impl From<SanError> for RenderError {
    fn from(err: SanError) -> Self {
        Self::San(err)
    }
}

impl From<io::Error> for RenderError {
    fn from(err: io::Error) -> Self {
        Self::Io(err)
    }
}

/// Render a Postal frpc config. `local_port` is the agent's loopback bind.
pub fn render_frpc_toml(spec: &FrpcSpec) -> Result<String, SanError> {
    let hostname = hostname_for_label(&spec.label)?;
    let label = crate::san::label_from_host(&hostname)?;
    let proxy_name = format!("postal-{label}");
    let port = if spec.local_port == 0 {
        crate::DEFAULT_LOCAL_PORT
    } else {
        spec.local_port
    };

    let mut out = String::new();
    out.push_str("# Postal (postal.bot) tunnel — generated by p5-agent.\n");
    out.push_str("# Treat as a secret when a token is present (file is 0600).\n\n");
    out.push_str(&format!("serverAddr = {}\n", toml_str(&spec.server_addr)));
    out.push_str(&format!("serverPort = {}\n", spec.server_port));
    out.push('\n');

    if let Some(token) = spec
        .token
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
    {
        out.push_str("[metadatas]\n");
        out.push_str(&format!("token = {}\n", toml_str(token)));
        out.push('\n');
    }

    out.push_str("[[proxies]]\n");
    out.push_str(&format!("name = {}\n", toml_str(&proxy_name)));
    out.push_str("type = \"https\"\n");
    out.push_str("localIP = \"127.0.0.1\"\n");
    out.push_str(&format!("localPort = {port}\n"));
    out.push_str(&format!("customDomains = [{}]\n", toml_str(&hostname)));
    Ok(out)
}

pub fn frpc_toml_path(root: &Path) -> PathBuf {
    root.join(TUNNEL_DIR).join(FRPC_TOML_FILE)
}

pub fn write_frpc_toml(root: &Path, spec: &FrpcSpec) -> Result<PathBuf, RenderError> {
    let dir = root.join(TUNNEL_DIR);
    fs::create_dir_all(&dir)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(&dir, fs::Permissions::from_mode(0o700));
    }
    let text = render_frpc_toml(spec)?;
    let dest = frpc_toml_path(root);
    let tmp = dest.with_extension("toml.tmp");
    let mut opts = OpenOptions::new();
    opts.write(true).create(true).truncate(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        opts.mode(0o600);
    }
    {
        let mut f = opts.open(&tmp)?;
        f.write_all(text.as_bytes())?;
        f.sync_all()?;
    }
    fs::rename(&tmp, &dest).inspect_err(|_| {
        let _ = fs::remove_file(&tmp);
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(&dest, fs::Permissions::from_mode(0o600));
    }
    Ok(dest)
}

fn toml_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec(port: u16) -> FrpcSpec {
        FrpcSpec {
            label: "acme".into(),
            local_port: port,
            server_addr: "127.0.0.1".into(),
            server_port: 7000,
            token: Some("tok_secret".into()),
        }
    }

    #[test]
    fn render_https_loopback_8443() {
        let toml = render_frpc_toml(&spec(8443)).unwrap();
        assert!(toml.contains("localIP = \"127.0.0.1\""), "{toml}");
        assert!(toml.contains("localPort = 8443"), "{toml}");
        assert!(toml.contains("type = \"https\""), "{toml}");
        assert!(
            !toml.contains("type = \"http\"\n"),
            "Postal v0 is https passthrough\n{toml}"
        );
        assert!(
            toml.contains("customDomains = [\"acme.postal.bot\"]"),
            "{toml}"
        );
        assert!(toml.contains("name = \"postal-acme\""), "{toml}");
        assert!(!toml.contains("k2.dev"), "{toml}");
        assert!(!toml.contains("k2so-"), "{toml}");
        assert!(toml.contains("token = \"tok_secret\""), "{toml}");
    }

    #[test]
    fn render_uses_agent_bind_port() {
        let toml = render_frpc_toml(&spec(18765)).unwrap();
        assert!(toml.contains("localPort = 18765"), "{toml}");
        assert!(toml.contains("localIP = \"127.0.0.1\""), "{toml}");
    }

    #[test]
    fn render_zero_port_defaults_8443() {
        let toml = render_frpc_toml(&spec(0)).unwrap();
        assert!(toml.contains("localPort = 8443"), "{toml}");
    }

    #[test]
    fn render_omits_token_when_blank() {
        let mut s = spec(8443);
        s.token = None;
        let toml = render_frpc_toml(&s).unwrap();
        assert!(!toml.contains("[metadatas]"), "{toml}");
        assert!(!toml.contains("token ="), "{toml}");
    }

    #[test]
    fn write_frpc_toml_is_0600() {
        let tmp = tempfile::tempdir().unwrap();
        let path = write_frpc_toml(tmp.path(), &spec(8443)).unwrap();
        let text = fs::read_to_string(&path).unwrap();
        assert!(text.contains("type = \"https\""));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = fs::metadata(&path).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o600, "frpc.toml must be 0600, got {mode:o}");
        }
    }

    #[test]
    fn debug_redacts_token() {
        let s = spec(8443);
        let dbg = format!("{s:?}");
        assert!(!dbg.contains("tok_secret"), "{dbg}");
        assert!(dbg.contains("<redacted>"), "{dbg}");
        assert!(dbg.contains("acme"), "{dbg}");
    }

    #[test]
    fn token_quotes_are_escaped() {
        let mut s = spec(8443);
        s.token = Some("ab\"c\nname = \"evil".into());
        let toml = render_frpc_toml(&s).unwrap();
        assert!(toml.contains(r#"token = "ab\"c\nname = \"evil""#), "{toml}");
    }
}
