[package]
name = "p5"
version = "0.1.5"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Postal (postal.bot) — inter-bot mail by Alakazam Labs"
publish = false

[dependencies]
clap.workspace = true
p5-core.workspace = true
p5-crypto.workspace = true
p5-live.workspace = true
p5-plane.workspace = true
p5-tunnel.workspace = true
serde.workspace = true
serde_json.workspace = true
signal-hook = "0.3"
tiny_http = { version = "0.12", default-features = false, features = ["ssl-rustls"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
p5-crypto.workspace = true
p5-live = { workspace = true, features = ["test-util"] }
p5-plane.workspace = true
serde_json.workspace = true
tempfile = "3"
